### PR TITLE
Create animals table

### PR DESCRIPTION
**Pull request by tonnymuchui**
- Created a database named vet_clinic :heavy_check_mark: 
- Created a table named animals :heavy_check_mark:
- Inserted data into animals table :heavy_check_mark:
- Query data from animals table :heavy_check_mark:
- Screenshot: https://drive.google.com/file/d/1X_2nGUGkrnQfhNAwEgkn8UkyhX8Ddi9J/view?usp=sharing

### CODE REVIEW

**Review by VICTOR-CHUKWU — CHANGES_REQUESTED** [review]
Hi @tonnymuchui  👋  

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

almost

## Highlights
- Good PR
- Good commit


## Required Changes ♻️

- [ ] your MIT link is broken, kindly fix it
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by tonnymuchui** [comment]
What do you mean by MiT link?.

**Comment by VICTOR-CHUKWU** [comment]
MIT link in your README file

**Review by jerryowusu — APPROVED** [review]
Hi @tonnymuchui 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

stingy-approved


## Highlights
Great job so far :heavy_check_mark: 

## Optional suggestions

- [ ] Your project readme file is missing a lot of important features which should have been cause of invalidation that the previous reviewer missed. For instance your project is missing the Key Features and Future Features. Also you have to customize and edit your readme file according to you and your project credentials. Kindly fix all these before merging to give your project a more professional and up to standard appeal. 

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
